version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: projedata
    restart: always
    environment:
      POSTGRES_DB: projedata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projedata_network

volumes:
  postgres_data:

networks:
  projedata_network:
    driver: bridge
